### ISSUE TITLE
✖ Error fetching channel list with error: Error: invalid_auth

### ISSUE THREAD

**Issue by cmcg13** [wearefine/slack-archive-bot#5] opened 2018-06-06 18:40 UTC
Hey folks,

Thanks for your stellar work on this project. I'm running into an issue trying to setup the tool in the CLI but I'm also a complete Slack Noob so this may be a simple error on my part. I believe I've set the ARCHIVEBOT_SLACK_TOKEN correctly in the Terminal. Any help you can provide would be greatly appreciated!

Thanks!

**Comment by cpitkin** [comment] 2018-06-06 18:49
@cmcg13 First off thanks for using the project. Can you provide me the following details so I can better point you in the right direction?

Provide the command you're running in the CLI. (make sure to not paste the actual token)
What version of the CLI are you running?
What version of Node are you running?

**Comment by cmcg13** [comment] 2018-06-06 19:01
Thanks for the quick response! Answers below:

1. Command is slack-archivebot ARCHIVEBOT_SLACK_TOKEN=token (I have also in vain tried slack-archivebot -t ARCHIVEBOT_SLACK_TOKEN =token)
2. 2.7.4
3. v8.11.2

**Comment by cpitkin** [comment] 2018-06-07 13:32
The issue is that you're not getting the commands and parameters in the right order. Once you get them in the right order you should be able to successfully run the CLI.

Using ARCHIVEBOT_SLACK_TOKEN environment variable
`ARCHIVEBOT_SLACK_TOKEN=token slack-archivebot`

Using the inline `-t` parameter
`slack-archivebot -t token`
**NOTE:** token above is just the token you get from Slack verbatim

**Comment by cmcg13** [comment] 2018-06-07 13:51
Thanks Charlie - that solved the authorization issue. I now appear to have a scope issue, however I've given the App the following permissions:

Administer the workspace
Add a bot user with the username @autoarchive	
Access user’s public channels
Access information about user’s public channels
Modify your public channels	
Send messages as Auto-Archive
Access user’s group messages
Access information about user’s group messages

Are there any additional permissions needed? Also forgive my ignorance, but does this need to be manually re-run by the user every few days or will it auto-run once set up correctly? Thanks for your help!

Error Code:

`✓ Fetching Slack channels
✖ Error fetching channel undefined with Error: missing_scope

/usr/local/lib/node_modules/slack-archivebot/index.js:139
        if (moment.duration(now - data.messages[0].ts, 's').asDays() > inactiveDays) {
                                       ^

TypeError: Cannot read property 'messages' of undefined
    at slack.channels.history (/usr/local/lib/node_modules/slack-archivebot/index.js:139:40)
    at _res (/usr/local/lib/node_modules/slack-archivebot/node_modules/slack/methods/_exec.js:39:7)
    at IncomingMessage.__end (/usr/local/lib/node_modules/slack-archivebot/node_modules/tiny-json-http/_write.js:75:9)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by cpitkin** [comment] 2018-06-07 14:31
The following scope will work:

Access user’s public channels: channels:history
Access information about user’s public channels: channels:read
Modify your public channels: channels:write

As for automating the archive process. The CLI doesn't support an automated mode. We use Jenkins internally to run the CLI in a container once a day. There are lots of different methods for running jobs on a schedule so I am not looking to add this feature to the current CLI.

**Comment by cmcg13** [comment] 2018-06-07 15:49
Thanks for your help Charlie. I was able to get it working correctly using the OAuth Access Token but not using the Bot User OAuth Access Token. Is there a restriction on running this process as a bot user? I'd prefer to have it run as a Bot just to keep my user name out of things.

Automation piece makes 100% sense - I will set up a Jenkins job to do just that. Thanks.

**Comment by cpitkin** [comment] 2018-06-07 16:04
We have ours currently setup using an App OAuth Token. So it acts just like an app in Slack. That route has worked great for us so far. Since the overall issue seems to be resolved I am going to close the issue. If you still have issues relating to auth please re-open the issue.

**Closed as completed by cpitkin** 2018-06-07 16:04 UTC
